const BLOCK_SIZE = 12;
const MAP_SIZE = 60;
const MAP_BOUNDARY = (MAP_SIZE - 1) * BLOCK_SIZE;
const UPDATE_INTERVAL = 1 / 15;
const PLAYER_INITIAL_LENGTH = 3;
const PLAYER_INITIAL_POSITION = {
  x: Math.floor(MAP_SIZE / 2) * BLOCK_SIZE,
  y: (MAP_SIZE - 2) * BLOCK_SIZE,
};
const PLAYER_INITIAL_DIRECTION = "up";

export {
  BLOCK_SIZE,
  MAP_SIZE,
  MAP_BOUNDARY,
  UPDATE_INTERVAL,
  PLAYER_INITIAL_LENGTH,
  PLAYER_INITIAL_POSITION,
  PLAYER_INITIAL_DIRECTION,
};
