const BLOCK_SIZE = 16;
const MAP_WIDTH = 80;
const MAP_HEIGHT = 45;
const UPDATE_INTERVAL = 1 / 15;
const PLAYER_INITIAL_LENGTH = 3;
const PLAYER_INITIAL_POSITION = {
  x: Math.floor(MAP_WIDTH / 2) * BLOCK_SIZE,
  y: (MAP_HEIGHT - 2) * BLOCK_SIZE,
};
const PLAYER_INITIAL_DIRECTION = "up";
const PLAYER_MAX_X = (MAP_WIDTH - 1) * BLOCK_SIZE;
const PLAYER_MAX_Y = (MAP_HEIGHT - 1) * BLOCK_SIZE;
const APPLE_MIN_QUANTITY = 16;

module.exports = {
  BLOCK_SIZE,
  MAP_WIDTH,
  MAP_HEIGHT,
  UPDATE_INTERVAL,
  PLAYER_INITIAL_LENGTH,
  PLAYER_INITIAL_POSITION,
  PLAYER_INITIAL_DIRECTION,
  PLAYER_MAX_X,
  PLAYER_MAX_Y,
  APPLE_MIN_QUANTITY,
};
