const BLOCK_SIZE = 14;
const MAP_SIZE = 140;
const UPDATE_INTERVAL = 1 / 20;
const PLAYER_INITIAL_LENGTH = 3;
const PLAYER_INITIAL_POSITION = {
  x: Math.floor(MAP_SIZE / 2) * BLOCK_SIZE,
  y: (MAP_SIZE - 2) * BLOCK_SIZE,
};
const PLAYER_INITIAL_DIRECTION = "up";

module.exports = {
  BLOCK_SIZE,
  MAP_SIZE,
  UPDATE_INTERVAL,
  PLAYER_INITIAL_LENGTH,
  PLAYER_INITIAL_POSITION,
  PLAYER_INITIAL_DIRECTION,
};
